workflows:
  default-workflow:
    name: Flutter CI
    max_build_duration: 30
    environment:
      flutter: stable          # Flutter preinstalado en Codemagic
      xcode: latest
    scripts:
       - name: Ensure Flutter project structure
    script: |
      if [ ! -d "android" ]; then
        echo "Generating missing native folders…"
        flutter create . --platforms=android,ios,web
      fi
      # ⚡ Elimina el test de plantilla que llama a MyApp
      if [ -f "test/widget_test.dart" ]; then
        rm test/widget_test.dart
        echo "Removed default widget_test.dart"
      fi
    - flutter pub get
    - flutter analyze
    - flutter test
    - flutter build apk --release
    - flutter build ios --release --no-codesign
    artifacts:
      - build/**/outputs/**/*.apk
      - build/ios/ipa/*.ipa
