workflows:
  default-workflow:
    name: Flutter CI
    max_build_duration: 30
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Ensure Flutter project structure
        script: |
          # Genera o regenera las carpetas nativas
          if [ ! -d "android" ]; then
            flutter create . --platforms=android,ios,web --overwrite
          fi

          # Limpia el test de plantilla
          [ -f test/widget_test.dart ] && rm test/widget_test.dart

          # Parchea packagingOptions SOLO si el archivo existe
          GRADLE_FILE="android/app/build.gradle"
          if [ -f "$GRADLE_FILE" ] && ! grep -q 'pickFirst "lib/.*/libc++_shared.so"' "$GRADLE_FILE"; then
            echo "Patching packagingOptions…"
            awk '
              /android[[:space:]]*{/ {
                print
                print "    packagingOptions {"
                print "        pickFirst \\\"lib/**/libc++_shared.so\\\""
                print "    }"
                next
              }
              { print }
            ' "$GRADLE_FILE" > "$GRADLE_FILE.tmp" && mv "$GRADLE_FILE.tmp" "$GRADLE_FILE"
          fi

      - flutter pub get
      - flutter clean
      - flutter analyze
      - flutter test
      - flutter build apk --release    # Reactiva iOS cuando el APK pase

    artifacts:
      - build/**/outputs/**/*.apk

    triggering:
      events: [push]
      branch_patterns:
        - pattern: "main"
          include: true

