workflows:
  default-workflow:
    name: Flutter CI
    max_build_duration: 35
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Generate native folders and patch build.gradle
        script: |
          if [ ! -d "android" ]; then
            flutter create . --platforms=android,ios,web --overwrite
          fi

          # Remove default test if exists
          [ -f test/widget_test.dart ] && rm test/widget_test.dart

          # Patch packagingOptions if needed
          GRADLE_FILE="android/app/build.gradle"
          if [ -f "$GRADLE_FILE" ] && ! grep -q 'pickFirst "lib/.*/libc++_shared.so"' "$GRADLE_FILE"; then
            awk '
              /android[[:space:]]*{/ {
                print
                print "    packagingOptions {"
                print "        pickFirst \\\"lib/**/libc++_shared.so\\\""
                print "    }"
                next
              }
              { print }
            ' "$GRADLE_FILE" > "$GRADLE_FILE.tmp" && mv "$GRADLE_FILE.tmp" "$GRADLE_FILE"
          fi

      - name: Clean cache and dependencies
        script: |
          flutter clean
          rm -rf ~/.pub-cache
          flutter pub get

      - name: Detect plugins using Android embedding v1
        script: |
          echo "=== Looking for v1 Android plugins ==="
          find ~/.pub-cache/hosted -type f -name "*.java" -exec grep -Hn "registerWith(Registrar" {} \; || echo "✅ No v1 plugins found"

      - flutter analyze
      - flutter test
      - name: Build APK (verbose)
        script: flutter build apk --release -v

    artifacts:
      - build/**/outputs/**/*.apk

    triggering:
      events: [push]
      branch_patterns:
        - pattern: "main"
          include: true
