workflows:
  default-workflow:
    name: Flutter CI
    max_build_duration: 30          # minutos
    environment:
      flutter: stable               # Canal «stable» preinstalado en Codemagic
      xcode: latest                 # Xcode 16 (SDK iOS 18)

   scripts:
  - name: Ensure Flutter project structure
    script: |
      if [ ! -d "android" ]; then
        echo "Generating missing native folders…"
        flutter create . --platforms=android,ios,web
      fi
      # Elimina test de plantilla
      if [ -f "test/widget_test.dart" ]; then
        rm test/widget_test.dart
      fi
      # 🩹 Parchear packagingOptions en build.gradle
      GRADLE_FILE="android/app/build.gradle"
      if ! grep -q "pickFirst \"lib/**/libc++_shared.so\"" "$GRADLE_FILE"; then
        echo "Patching packagingOptions…"
        # Inserta líneas justo después de 'android {' bloque
        sed -i.bak '/android {/a \
    packagingOptions {\n        pickFirst "lib/**/libc++_shared.so"\n    }' "$GRADLE_FILE"
      fi
  - flutter pub get
  - flutter clean
  - flutter analyze
  - flutter test
  - flutter build apk --release -v
  # - flutter build ios --release --no-codesign   # reactiva cuando APK pase

    artifacts:
      # Archivos de salida que Codemagic mostrará para descargar
      - build/**/outputs/**/*.apk
      - build/ios/ipa/*.ipa
    # Opcional: dispara automáticamente en cada push a main
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
